[auth]
enabled = true
site_url = "https://yo-hablo.vercel.app"
additional_redirect_urls = ["http://127.0.0.1:3000/*", "http://localhost:3000/*", "http://localhost:5173/*"]

[auth.external]
enabled = true

[auth.external.google]
enabled = true
client_id = ""
secret = ""
redirect_uri = "https://owkfrpuydxwznqxibgng.supabase.co/auth/v1/callback"
